services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: postgres
    ports:
    - "5432:5432"
    volumes:
    - ./local_data:/var/lib/postgresql/data

  
    
  
